apiVersion: v1
kind: Service
metadata:
  name: hdfs
spec:
  selector:
    name: hdfs
  clusterIP: None
  ports:
  - name: hdfs
    port: 9000
    targetPort: 9000
---

apiVersion: v1
kind: Pod
metadata:
  name: hdfs
  labels:
    name: hdfs
spec:
  containers:
    - image: gaborgsomogyi/hdfs:latest
      imagePullPolicy: Never
      securityContext:
        capabilities:
          add: ["DAC_READ_SEARCH", "SYS_NICE"]
      name: hdfs
      volumeMounts:
        - mountPath: /share
          name: volume
  volumes:
    - name: volume
      hostPath:
        path: /share
        type: Directory
